# Generated by Django 5.1 on 2024-11-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_clienteo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('fecha_nac', models.DateField(verbose_name='')),
                ('domicilio', models.CharField(max_length=6)),
                ('curp', models.CharField(max_length=6)),
            ],
        ),
    ]
