# Generated by Django 5.1 on 2024-11-25 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='id_clienteo',
            new_name='id_cliente',
        ),
    ]
