# Generated by Django 5.1 on 2024-11-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id_ingrediente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('id_provedor', models.CharField(max_length=6)),
                ('id_producto', models.CharField(max_length=6)),
                ('tipo_carne', models.CharField(max_length=100)),
                ('id_categoria', models.CharField(max_length=6)),
            ],
        ),
    ]
