# Generated by Django 5.1 on 2024-11-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id_trabajador', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=100)),
                ('fecha_nac', models.DateField()),
                ('curp', models.CharField(max_length=100)),
                ('salario', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
