# Generated by Django 5.1 on 2024-11-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('horario', models.DateTimeField(verbose_name='')),
                ('num_trabajadores', models.CharField(max_length=6)),
                ('direcccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('id_ventas', models.CharField(max_length=6)),
                ('correo', models.CharField(max_length=100)),
            ],
        ),
    ]
