# Generated by Django 5.1 on 2024-11-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='horario',
            field=models.CharField(max_length=100),
        ),
    ]
