# Generated by Django 5.1.3 on 2024-11-27 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales_app', '0002_alter_sucursal_horario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sucursal',
            old_name='direcccion',
            new_name='direccion',
        ),
    ]
